visualization/detection/urls.py
from django.conf.urls import url
from . import views

app_name = 'detection'

urlpatterns = [
    url(r'^view_image/(.*)/(.*)/(.*)/([0-9]+)$', 
        views.view_image, 
        name='view_image'),
    url(r'taxonomy_validation_result/$',
        views.validate_taxonomy,
        name='taxonomy_validation_result'),
    url(r'^view_image/$', 
        views.view_image2, 
        name='view_image2'),
    url(r'^taxonomy_verification/$',
        views.input_taxonomy,
        name='taxonomy_verification'),
    url(r'^view_tree/$', 
        views.view_tree, 
        name='view_tree'),
    url(r'^check_mapping/$', 
        views.check_mapping, 
        name='check_mapping'),
    # if no parameter is given -> show all the exps
    # if full_expid is given -> show all the prediction results, i.e. *.predict
    # file
    # if full_expid is given and file name of predict file is given -> show the
    # prediction results. 
    # old scenario: full_expid is not specified. 
    url(r'^view_model/$', 
        views.view_model,
        name='view_model'),
    url(r'^media/(.*)$',
        views.download_file,
        name='return_file'),
]

visualization/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^detection/', include('detection.urls')),
    url(r'^admin/', admin.site.urls),
]

visualization/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

visualization/detection/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class File(models.Model):
    file = models.FileField(upload_to = './')
    name = models.CharField(max_length = 255)

visualization/detection/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
import sys
import os
import os.path as op
def get_qd_root():
    return op.dirname(op.dirname(op.dirname(op.realpath(__file__))))
import os.path as op
sys.path.append(op.join(get_qd_root(), 'scripts'))
from tsv_io import tsv_reader
from qd_common import write_to_file
from process_tsv import TSVFile
from process_tsv import ImageTypeParser
from process_tsv import visualize_box
from process_image import draw_bb, show_image, save_image
import base64
from yolotrain import CaffeWrapper
from tsv_io import load_labels
from process_tsv import update_confusion_matrix
from pprint import pformat
import os
from yolotrain import get_confusion_matrix
from qd_common import readable_confusion_entry
from process_tsv import gt_predict_images
from qd_common import get_target_images
from tsv_io import get_all_data_info
from tsv_io import get_all_data_info2
from qd_common import get_all_model_expid
from qd_common import get_parameters_by_full_expid
from process_tsv import get_confusion_matrix_by_predict_file
from qd_common import get_all_predict_files
from qd_common import parse_data, parse_test_data
from tsv_io import load_labelmap
from process_tsv import gen_html_tree_view
from qd_common import get_all_tree_data
from qd_common import init_logging
from django.http import HttpResponseRedirect
from django.urls import reverse
import cv2
from django import template
import simplejson as json
from process_tsv import build_taxonomy_impl
import sys
import traceback2 as traceback
from .models import *
import django.core.files
import logging
import uuid
from qd_common import load_class_ap
import json

init_logging()

def run_in_qd(func, *args, **kwargs):
    curr_dir = os.curdir
    os.chdir(get_qd_root())
    r = func(*args, **kwargs)
    os.chdir(curr_dir)
    return r

def serve_file(filename):
    response = HttpResponse(content_type="text/html")
    for line in open(filename):
        response.write(line)
    return response

def check_mapping(request):
    print request.method
    if request.method == 'POST':
        return HttpResponse(json.dumps({'message': 'good'}))
    else:
        return render(request, 'detection/category_viewer.html')
        #return serve_file(op.join(get_qd_root(),
            #'data/Tax4k_V1_6/category_viewer3/index.html'))

def view_tree(request):
    if 'data' in request.GET:
        data = request.GET.get('data')
        s = run_in_qd(gen_html_tree_view, data)
        context = {'li_ul_tree_str': s}
        return render(request, 'detection/view_tree.html', context)
    else:
        data_list = run_in_qd(get_all_tree_data)
        context = { 'data_names': data_list }
        return render(request, 'detection/view_list_has_tree.html', context)

def view_single_model(request):
    '''
    deprecated
    '''
    data = request.GET.get('data', 'office_v2.12')
    net = request.GET.get('net', 
            'darknet19_448')
    test_data = request.GET.get('test_data', 
            data)
    expid = request.GET.get('expid', 
            'A_noreorg_burnIn5e.1_tree_initFrom.imagenet.A_bb_nobb')
    label = request.GET.get('filter_label', 'any')
    start_id = int(float(request.GET.get('start_id', '0')))
    threshold = 0.1
    
    extra_param = {}
    if 'test_input_sizes' in request.GET:
        extra_param['test_input_sizes'] = [int(float(s)) for s in
            request.GET.getlist('test_input_sizes')]
    # qd code
    curr_dir_backup = os.getcwd()
    os.chdir(get_qd_root())
    x = get_confusion_matrix(data, 
            net, test_data, expid, threshold, **extra_param)
    predicts, gts, label_to_idx = x['predicts'], x['gts'], x['label_to_idx']
    confusion_pred_gt = x['confusion_pred_gt']
    confusion_gt_pred = x['confusion_gt_pred']
    os.chdir(curr_dir_backup)
    image_pairs = []
    target_images, image_aps = get_target_images(predicts, gts, label, threshold)
    pairs = gt_predict_images(predicts, gts, test_data, target_images,
            start_id,
            threshold, label_to_idx, image_aps)
    max_pairs = 10
    for i, (key, im_gt, im_pred, ap) in enumerate(pairs):
        path_gt = save_image_in_static(im_gt, '{}/{}/{}/{}/{}_gt.png'.format(
            data, net, expid, test_data, key))
        path_pred = save_image_in_static(im_pred, '{}/{}/{}/{}/{}_pred.png'.format(
            data, net, expid, test_data, key))
        image_pairs.append((path_gt, path_pred, ap))
        if i >= max_pairs - 1:
            break
    
    common_param = [('data', data), ('net', net), ('expid', expid),
            ('filter_label', label), ('test_data', test_data)]
    for key in extra_param:
        value = extra_param[key]
        if type(value) is list:
            for v in value:
                common_param.append((key, str(v)))
        else:
            assert False
    previous_param = []
    previous_param.extend(common_param)
    previous_start_id = start_id - max_pairs
    if previous_start_id < 0:
        total_images = len(target_images)
        previous_start_id = previous_start_id + total_images
    previous_param.append(('start_id', str(max(0, previous_start_id))))
    next_param = []
    next_param.extend(common_param)
    next_param.append(('start_id', str(start_id + len(image_pairs))))
    previous_button_param = '&'.join(['{}={}'.format(key, value) for key, value
        in previous_param])
    next_button_param = '&'.join(['{}={}'.format(key, value) for key, value in 
        next_param])
    
    if label not in confusion_pred_gt:
        html_confusion_pred_gt = []
    else:
        html_confusion_pred_gt = readable_confusion_entry(
                confusion_pred_gt[label])
    context = {
            'previous_button_param': previous_button_param,
            'next_button_param': next_button_param,
            'label': label,
            'confusion_pred_gt': html_confusion_pred_gt,
            'confusion_gt_pred': readable_confusion_entry(
                confusion_gt_pred[label]),
            'image_pairs': image_pairs}

    return render(request, 'detection/predict_result.html', context)


def view_exp_list(request):
    curr_dir = os.curdir
    os.chdir(get_qd_root())
    full_expids = get_all_model_expid()
    os.chdir(curr_dir)
    full_expids.sort()
    context = {'full_expids': full_expids}
    return render(request, 'detection/exp_list.html', context)

def view_model_by_predict_file(request, full_expid, predict_file, 
        label, start_id, threshold):
    start_id = int(float(start_id))
    threshold = float(threshold)
    
    # qd code
    curr_dir_backup = os.getcwd()
    os.chdir(get_qd_root())
    data = parse_data(full_expid)
    test_data, test_data_split = parse_test_data(predict_file)
    x = get_confusion_matrix_by_predict_file(full_expid, predict_file,
            threshold)
    predicts, gts, label_to_idx = x['predicts'], x['gts'], x['label_to_idx']
    confusion_pred_gt = x['confusion_pred_gt']
    confusion_gt_pred = x['confusion_gt_pred']
    os.chdir(curr_dir_backup)

    image_pairs = []
    target_images, image_aps = get_target_images(predicts, gts, label, threshold)
    pairs = gt_predict_images(predicts, gts, test_data, target_images,
            label,
            start_id,
            threshold, label_to_idx, image_aps, test_data_split)
    max_pairs = 10
    for i, (key, im_origin, im_gt_target, im_pred_target, im_gt, im_pred, ap) in enumerate(pairs):
        path_origin = save_image_in_static(im_origin, '{}/{}_origin.png'.format(
            data, key))
        path_gt_target = save_image_in_static(im_gt_target, '{}/{}_gt_target.png'.format(
            data, key))
        path_gt = save_image_in_static(im_gt, '{}/{}_gt.png'.format(
            data, key))
        path_pred = save_image_in_static(im_pred, '{}/{}/{}_pred.png'.format(
            full_expid, predict_file, key))
        path_pred_target = save_image_in_static(im_pred_target,
                '{}/{}/{}_pred_target.png'.format(full_expid, predict_file, key))
        image_pairs.append((path_origin, path_gt_target, path_pred_target, path_gt, path_pred, ap))
        if i >= max_pairs - 1:
            break
    
    common_param = [('full_expid', full_expid), 
            ('predict_file', predict_file), 
            ('filter_label', label),
            ('threshold', threshold)]
    previous_param = []
    previous_param.extend(common_param)
    previous_start_id = start_id - max_pairs
    if previous_start_id < 0:
        total_images = len(target_images)
        previous_start_id = previous_start_id + total_images
    previous_param.append(('start_id', str(max(0, previous_start_id))))
    next_param = []
    next_param.extend(common_param)
    next_param.append(('start_id', str(start_id + len(image_pairs))))
    previous_button_param = '&'.join(['{}={}'.format(key, value) for key, value
        in previous_param])
    next_button_param = '&'.join(['{}={}'.format(key, value) for key, value in 
        next_param])
    
    if label not in confusion_pred_gt:
        html_confusion_pred_gt = []
    else:
        html_confusion_pred_gt = readable_confusion_entry(
                confusion_pred_gt[label])
    if label not in confusion_gt_pred:
        html_confusion_gt_pred = []
    else:
        html_confusion_gt_pred = readable_confusion_entry(
                confusion_gt_pred[label])
    context = {
            'previous_button_param': previous_button_param,
            'next_button_param': next_button_param,
            'label': label,
            'confusion_pred_gt': html_confusion_pred_gt,
            'confusion_gt_pred': html_confusion_gt_pred,
            'image_pairs': image_pairs}

    return render(request, 'detection/predict_result.html', context)

def view_model_prediction_labelmap(request, full_expid, predict_file):
    curr_dir = os.curdir
    os.chdir(get_qd_root())

visualization/detection/templates/detection/category_viewer.html
<html>
    <head>
        <style>table, th, td {border: 1px solid black;}
        </style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
$('#form').submit(function(e){
    e.preventDefault();
    $('#form').hide()
    <!--$.post('', $(this).serialize(), function(data){ ... });-->
});
    </script>
    </head>
        <body><h1>Matched Images</h1>
            <table>
                                <tr>
                    <td> 1 </td>
                    <td>aerial photography</td>
                                        <td> 
                                                mturk700_url_as_key: aerial photography 
                        </br>
                        <img src=mturk700_url_as_key/5507580807494603276_aerialphotography.jpg style="width:300px"/>
                        </br>
                        <div>
                            <form action="" method="post" id="form"> {% csrf_token %} 
                            <input type="submit" value="Submit"/>
                        </form>
                        </div>

                                            </td>
                                    </tr>
                                <tr>
                    <td> 2 </td>
                    <td>black and white</td>
                                        <td> 
                                                mturk700_url_as_key: black and white 
                        </br>
                        <img src=mturk700_url_as_key/-4742021112566986664_blackandwhite.jpg style="width:300px"/>
                        </br>
                                            </td>
                                        <td> 
                                                VisualGenomeClean: black and white 
                        </br>
                        <img src=VisualGenomeClean/1513597235019779783_blackandwhite.jpg style="width:300px"/>
                        </br>
                                            </td>
                                    </tr>
                                <tr>
                    <td> 3 </td>
                    <td>cartoon</td>
                                        <td> 
                                                mturk700_url_as_key: cartoon 
                        </br>
                        <img src=mturk700_url_as_key/8469802826186483623_cartoon.jpg style="width:300px"/>
                        </br>
                                            </td>
                                        <td> 
                                                VisualGenomeClean: cartoon 
                        </br>
                        <img src=VisualGenomeClean/4814035714618610382_cartoon.jpg style="width:300px"/>
                        </br>
                                            </td>
                                        <td> 
                                                4000_Full_set: cartoon 
                        </br>
                        <img src=4000_Full_set/4184836860563555378_cartoon.jpg style="width:300px"/>
                        </br>
                                            </td>
                                    </tr>
                                <tr>
                    <td> 4 </td>
                    <td>clip art</td>
                                        <td> 
                                                4000_Full_set: clip art 
                        </br>
                        <img src=4000_Full_set/-1851855325198941950_clipart.jpg style="width:300px"/>
                        </br>
                                            </td>
                                    </tr>
                                <tr>
                    <td> 5 </td>
                    <td>collage</td>
                                        <td> 
                                                mturk700_url_as_key: collage 
                        </br>
                        <img src=mturk700_url_as_key/3590529075632587693_collage.jpg style="width:300px"/>
                        </br>
                                            </td>
                                        <td> 
                                                VisualGenomeClean: collage 
                        </br>
                        <img src=VisualGenomeClean/-8377893803450769436_collage.jpg style="width:300px"/>
                        </br>
                                            </td>
                                        <td> 
                                                4000_Full_set: collage 
                        </br>
                        <img src=4000_Full_set/-8450167044269670066_collage.jpg style="width:300px"/>
                        </br>
                                            </td>
                                    </tr>
                            </table>
        </body>
</html>

visualization/detection/templates/detection/data_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<script>
      window.onload = function  () {
    	var li_ul = document.querySelectorAll(".col_ul li  ul");
        for (var i = 0; i < li_ul.length; i++) {
            li_ul[i].style.display = "none"
        };
    
        var exp_li = document.querySelectorAll(".col_ul li > span");
        for (var i = 0; i < exp_li.length; i++) {
            exp_li[i].style.cursor = "pointer";
            exp_li[i].onclick = showul;
        };
        function showul () {
            nextul = this.nextElementSibling;
            if(nextul.style.display == "block")
                nextul.style.display = "none";
            else
                nextul.style.display = "block";
        }
    }
  </script>
	<style type="text/css">
	</style>
</head>

<body>
    <ul>
    {% for name in names %}
    <li><a href="{% url 'detection:view_image2' %}?data={{ name }}">{{ name }}</a>
    </li>
    {% endfor %}
    </ul>
</body>
</html>

visualization/detection/templates/detection/display_tax_results.html
<!DOCTYPE html>
<html>
<body>

<h3>Taxonomy Validation Results</h3>

<p>{{error|linebreaksbr}}</p>

{% for file_ob in files %}
<a href='{{ file_ob.file.url }}' download>{{ file_ob.name }}</a>
<br/>
{% endfor %}


</script>

</body>
</html>

visualization/detection/templates/detection/exp_list.html
<ul>
    {% for full_expid in full_expids %}
    <li><a href="{% url 'detection:view_model' %}?full_expid={{ full_expid }}">{{ full_expid }}</a></li>
    {% endfor %}
</ul>

visualization/detection/templates/detection/get_tax_info.html
<!DOCTYPE html>

{% load static %}
<html>
<body>

<h3>Taxonomy Validator</h3>

<form enctype="multipart/form-data" method="POST">
  {% csrf_token %}
  <label>Please input a dataset name, e.g. Tax4K_V1_7: Note: if the dataset name exists, we skip to create a newer one.</label> <br>
  <input type="text" name="out_data" size="150" value="" required> <br>
  <label>Data Sources seperated by comma: </label> <br>
  <input type="text" name="str_datas" value="{{ str_datas }}" size="150"/> <br><br>
  <input type="file" value="Browse" name="file_input" required=true> <br><br>
  <input type="submit" value="Submit" />
</form>

</body>
</html>

visualization/detection/templates/detection/image_overview.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<script>
      window.onload = function  () {
    	var li_ul = document.querySelectorAll(".col_ul li  ul");
        for (var i = 0; i < li_ul.length; i++) {
            li_ul[i].style.display = "none"
        };
    
        var exp_li = document.querySelectorAll(".col_ul li > span");
        for (var i = 0; i < exp_li.length; i++) {
            exp_li[i].style.cursor = "pointer";
            exp_li[i].onclick = showul;
        };
        function showul () {
            nextul = this.nextElementSibling;
            if(nextul.style.display == "block")
                nextul.style.display = "none";
            else
                nextul.style.display = "block";
        }
    }
  </script>
	<style type="text/css">
	</style>
</head>

<body>
    <ul class="col_ul">
    {% for name, split_version_labels in name_splits_labels %}
    <li><span>{{ name }}</span>
        <ul>
            {% for split, version, labels in split_version_labels %}
            <li><span>{{ split }} - {{ version }}</span>
                <ul>
                    {% for l in labels %}
                    <li>
                        <a href="{% url 'detection:view_image2' %}?data={{ name }}&split={{ split }}&version={{ version }}&label={{ l }}&start_id=0">{{ l }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
    </ul>
</body>
</html>

visualization/detection/templates/detection/images.html
{% load static %}

<style>
    table#image_table {
        border-collapse: collapse;
        margin-left: auto;
        margin-right: auto;
    }

    ul#label_list {
        list-style: none;
    }

</style>
<script src={% static "js/image_draw.js" %} type="text/javascript"></script>
<script>
    let images_dict = JSON.parse("{{ images|escapejs }}");
    let label_list = JSON.parse("{{ label_list|escapejs }}");
    let unchecked_list = [];

    let static_filepath = {% static null %};

    window.onload = function() {
        draw_images(images_dict, static_filepath, label_list);
    };

    function onClick_abstraction() {
        if (this.checked) {
            let index = unchecked_list.indexOf(this.id);
            unchecked_list.splice(index, 1);
        } else {
            unchecked_list.push(this.id);
        }

        update_images(images_dict, static_filepath, unchecked_list);
    }
</script>


<ul id="label_list">
    <li>Labels</li>
</ul>

<table id="image_table">
        <tr>
            <th>Raw Image</th>
            <th>Image with target labels</th>
            <th>Image with all labels</th>
        </tr>
</table>



<center>
    {% if label %}
    <a href="{% url 'detection:view_image2' %}?data={{ data }}&split={{ split }}&version={{ version }}&label={{ label }}&start_id={{ previous_id }}">Previous</a>
    <a href="{% url 'detection:view_image2' %}?data={{ data }}&split={{ split }}&version={{ version }}&label={{ label }}&start_id={{ next_id }}">Next</a>
    {% else %}
        <a href="{% url 'detection:view_image2' %}?data={{ data }}&label={{ label }}&start_id={{ previous_id }}">Previous</a>
        <a href="{% url 'detection:view_image2' %}?data={{ data }}&label={{ label }}&start_id={{ next_id }}">Next</a>
    {% endif %}
</center>

visualization/detection/templates/detection/model_list.html
<ul>
    {% for full_expid in full_expids %}
    <li><a href="{% url 'detection:view_model' %}?full_expid={{ full_expid }}">{{ full_expid }}</a></li>
    {% endfor %}
</ul>

visualization/detection/templates/detection/predict_result.html
{% load static %}
<style>
    tr.seperated td {
        border-bottom: 1px solid black;
    }
    table {
        border-collapse: collapse;
        margin-left: auto;
        margin-right: auto;
    }
</style>

<table>
    <tr>
        <td>predict as <b>{{ label }}</b></td>
        <td>gt label </td>
        {% for item in confusion_pred_gt %}
        <td>{{ item.0 }}</td>
        {% endfor %}
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>count</td>
        {% for item in confusion_pred_gt %}
        <td>{{ item.1 }}</td>
        {% endfor %}
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>percent</td>
        {% for item in confusion_pred_gt %}
        <td>{{ item.2 }}</td>
        {% endfor %}
    </tr>
    <tr class='seperated'>
        <td>&nbsp;</td>
        <td>cum percent</td>
        {% for item in confusion_pred_gt %}
        <td>{{ item.3 }}</td>
        {% endfor %}
    </tr>
    <tr>
        <td>gt as <b>{{ label }}</b></td>
        <td>predict label </td>
        {% for item in confusion_gt_pred %}
        <td>{{ item.0 }}</td>
        {% endfor %}
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>count</td>
        {% for item in confusion_gt_pred %}
        <td>{{ item.1 }}</td>
        {% endfor %}
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>percent</td>
        {% for item in confusion_gt_pred %}
        <td>{{ item.2 }}</td>
        {% endfor %}
    </tr>
    <tr class='seperated'>
        <td>&nbsp;</td>
        <td>cum percent</td>
        {% for item in confusion_gt_pred %}
        <td>{{ item.3 }}</td>
        {% endfor %}
    </tr>
</table>


<table>
    <tr>
        <th>AP on {{ label }}</th>
        <th>Original image</th>
        <th>Ground truth with target label</th>
        <th>Prediction with target label</th>
        <th>Ground truth</th>
        <th>Prediction</th>
    </tr>
    {% for im_origin, im_gt_target, im_pred_target, im_gt, im_pred, ap in image_pairs %}
    <tr>
        <td>{{ ap }}</td>
        <td><img src="{% static im_origin %}" width=600></td>
        <td><img src="{% static im_gt_target %}" width=600></td>
        <td><img src="{% static im_pred_target %}" width=600></td>
        <td><img src="{% static im_gt %}" width=600></td>
        <td><img src="{% static im_pred %}" width=600></td>
    </tr>
    {% endfor %}
</table>

<a href="{% url 'detection:view_model' %}?{{ previous_button_param }}">Previous</a>
<a href="{% url 'detection:view_model' %}?{{ next_button_param }}">Next</a>
<!--<a href="{% url 'detection:view_model' %}">Next</a>-->

visualization/detection/templates/detection/view_list_has_tree.html
<ul class="col_ul">
    {% for data in data_names %}
    <li><a href="{% url 'detection:view_tree' %}?data={{ data }}">{{ data }}</a></li>
    {% endfor %}
</ul>

visualization/detection/templates/detection/view_model_prediction.html
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<script>
      window.onload = function  () {
    	var li_ul = document.querySelectorAll(".col_ul li  ul");
        for (var i = 0; i < li_ul.length; i++) {
            li_ul[i].style.display = "none"
        };
    
        var exp_li = document.querySelectorAll(".col_ul li > span");
        for (var i = 0; i < exp_li.length; i++) {
            exp_li[i].style.cursor = "pointer";
            exp_li[i].onclick = showul;
        };
        function showul () {
            nextul = this.nextElementSibling;
            if(nextul.style.display == "block")
                nextul.style.display = "none";
            else
                nextul.style.display = "block";
        }
    }
  </script>
</head>

<p>there are {{ prediction_files|length }} models</p>

<ul class="col_ul">
    {% for prediction_file in prediction_files %}
    <li><a href="{% url 'detection:view_model' %}?full_expid={{ full_expid }}&predict_file={{ prediction_file }}">{{ prediction_file }}
    </li>
    {% endfor %}
</ul>

visualization/detection/templates/detection/view_model_prediction_labelmap.html
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<script>
      window.onload = function  () {
    	var li_ul = document.querySelectorAll(".col_ul li  ul");
        for (var i = 0; i < li_ul.length; i++) {
            li_ul[i].style.display = "none"
        };
    
        var exp_li = document.querySelectorAll(".col_ul li > span");
        for (var i = 0; i < exp_li.length; i++) {
            exp_li[i].style.cursor = "pointer";
            exp_li[i].onclick = showul;
        };
        function showul () {
            nextul = this.nextElementSibling;
            if(nextul.style.display == "block")
                nextul.style.display = "none";
            else
                nextul.style.display = "block";
        }
    }
  </script>
</head>

<p>{{ prediction_file }}</p>

<ul class="col_ul">
    {% for l, ap in labelmap_ap %}
    <li><a href="{% url 'detection:view_model' %}?full_expid={{ full_expid }}&predict_file={{ prediction_file }}&filter_label={{ l }}&start_id=0&threshold=0.2">{{ l }}</a>
        {% if ap %}
        [{{ ap }}]
        {% endif %}
    </li>
    {% endfor %}
    </ul>
</ul>

visualization/detection/templates/detection/view_tree.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css"
    />
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
	<meta charset="UTF-8">
	<title>Document</title>
	<style type="text/css">
	</style>
</head>

<body>
    <p>
    label_name: (num_images_with_bb_in_total, 
                num_images_with_bb_in_train,
                num_images_with_bb_in_test);
                (num_images_no_bb_in_total,
                num_images_no_bb_in_train,
                num_images_no_bb_in_test)
    Source dataset name[matched_label
                (num_images_in_total, 
                num_images_in_train, 
                num_images_in_test)]
    <br>
    <ul>
        <li>num_images does not include the number of images from the children
        nodes</li>
        <li>num_images=-1 means we don't use the images from that data
        source for the specific purpose (train/test) or 
        please ignore it if the dataset was created before 4/29/2018</li>
        <li>matched_label = None means we will not extract any images from that
            data source.
        </li>
        <li>number of training images could be larger than the number of images
            in total because we will duplicate the training images so that the
            number is larger than 200 (by default)
        </li>
    </ul>
    
    </p>
    <div id='container'>
    <ul class="col_ul">
        {{ li_ul_tree_str | safe }}
    </ul>
    </div>

    <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">
    </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
    <script>
        $('#container').jstree();
    </script>
</body>
</html>